name: CI pipeline

on:
  push:
    branches:
      # - 'feature/**'
      - 'main'
env:
  DOCKER_IMAGE_NAME: 'dotnet_sdk_checker'
  GHCR_IMAGE_NAME: 'test_github_ci'

jobs:
  sayHello:
    runs-on: 'ubuntu-latest'

    steps:
      - name: bash to compute
        run: |
          echo "just saying hi"
          ls -la > ./rough
          cat ./rough
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: build solution
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
  docker_build_and_push:
    runs-on: 'ubuntu-latest'
    needs: build
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: get docker tag
        id: time
        run: echo "TAG=$(date +'%y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: echo the docker image name
        run: echo 'docker image --> ${{ env.DOCKER_IMAGE_NAME }}'
      - name: build docker image
        run: |
          echo 'building docker image ....'
          docker build -t ${{secrets.DOCKER_USERNAME}}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG }} .
      - name: docker push image
        run: |
          echo 'pushing to docker hub'
          docker push ${{secrets.DOCKER_USERNAME}}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG }}
  GHCR_build_and_push:
    runs-on: 'ubuntu-latest'
    needs: build
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: login to GHCR
        run: |
          docker login --username xenon-92 --password ${{secrets.GHCR_PAT_X}} ghcr.io
      - name: get docker tag
        id: time
        run: echo "TAG=$(date +'%y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: echo the docker image name
        run: echo 'docker image --> ${{ env.DOCKER_IMAGE_NAME }}'
      - name: build GHCR image
        run: |
          docker build -t ghcr.io/xenon-92/${{ env.GHCR_IMAGE_NAME }}:${{ env.TAG }} .
          docker push ghcr.io/xenon-92/${{ env.GHCR_IMAGE_NAME }}:${{ env.TAG }}
      - name: push GHCR image
        run: |
          docker push ghcr.io/xenon-92/${{ env.GHCR_IMAGE_NAME }}:${{ env.TAG }}
## The below step publishes this project as nuget, which we don't want ###
  Generate_SDK_and_Github_Publish:
    runs-on: 'ubuntu-latest'
    needs: [GHCR_build_and_push, docker_build_and_push]
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      
      - name: Pack NuGet package
        run: dotnet pack --configuration Release --output ./nupkg /p:PackageVersion=1.0.${{ github.run_number }}
        
      - name: Publish NuGet package to GitHub Packages
        run: dotnet nuget push ./nupkg/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GHCR_PAT_X }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Generate_auto_gen_client_and_publish:
    runs-on: 'ubuntu-latest'
    needs: [GHCR_build_and_push, docker_build_and_push]
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - uses: microsoft/setup-kiota@v0.5.0
      - name: create and build class library in autogen-clients
        run: |
          cd autogen-client
          cp ../openapi.yaml ./sdk.yml
          dotnet new classlib -o NMS-Client
          cd NMS-Client
          dotnet add package Microsoft.Kiota.Bundle
          kiota generate -l CSharp -c NMSClient -n NMS.Client -d ../sdk.yml -o ./Client
          dotnet build
      - name: Pack NuGet Package
        run: |
          cd autogen-client/NMS-Client
          dotnet pack --configuration Release -p:PackageVersion=1.0.${{ github.run_number }}
      - name: Publish NuGet Package
        run: |
          cd autogen-client/NMS-Client
          dotnet nuget push bin/Release/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GHCR_PAT_X }}
  Generate_auto_gen_client_and_publish_for_POST_API:
    runs-on: 'ubuntu-latest'
    needs: [GHCR_build_and_push, docker_build_and_push]
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - uses: microsoft/setup-kiota@v0.5.0
      - name: create and build class library in autogen-clients
        run: |
          cd autogen-client
          cp ../postapi.yaml ./sdk.yml
          dotnet new classlib -o POSTAPI_Client
          cd POSTAPI_Client
          dotnet add package Microsoft.Kiota.Bundle
          kiota generate -l CSharp -c PostsClient -n Posts.Client -d ../sdk.yml -o ./Client
          rm Class1.cs
          dotnet build
      - name: Pack NuGet Package
        run: |
          cd autogen-client/POSTAPI_Client
          dotnet pack --configuration Release -p:PackageVersion=1.0.${{ github.run_number }}
      - name: Publish NuGet Package
        run: |
          cd autogen-client/POSTAPI_Client
          dotnet nuget push bin/Release/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GHCR_PAT_X }}
  Stress_test_using_graffana_k6:
    runs-on: 'ubuntu-latest'
    needs: [Generate_auto_gen_client_and_publish_for_POST_API, Generate_auto_gen_client_and_publish]
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Install k6
        run: |
          sudo apt-get install -y gpg
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6
          echo "graffana k6 installed successfully!!!!!"
      - name: run stress test
        run: |
          cd graffana-test
          k6 run my-test.js --out json=stress_test.json
      - name: display stress test JSON result
        run: |
          cd graffana-test
          cat stress_test.json